### ISSUE TITLE
commandline doesn't appear in terminal

### ISSUE THREAD

**Issue by ghost** [freeCompilerCamp/freecompilercamp.github.io#9]
I get this message on this page: https://freecompilercamp.org/llvm-ir/

"If the commandline doesn't appear in the terminal, make sure popups are enabled or try resizing the browser window. If you are behind firewall, please open the firewall of your computer. Time remaining in this session : 1h 59m"

Hope this can be fixed soon :)

**Comment by ghost** [comment]
Btw I already tried the suggestions but they didn't work.

**Comment by chunhualiao** [comment]
The project runs out of funding. We had to turn off the AWS instance. Sorry
about that.

**Comment by ghost** [comment]
That's too bad, but totally understandable! Sorry to hear. I appreciate it!!! :)
